import * as RR from "react-router-dom/dist/index.js";

export const BrowserRouter = RR.MemoryRouter;
export const HashRouter = RR.HashRouter;
export const MemoryRouter = RR.MemoryRouter;
export const Routes = RR.Routes;
export const Route = RR.Route;
export const Link = RR.Link;
export const NavLink = RR.NavLink;
export const Navigate = RR.Navigate;
export const Outlet = RR.Outlet;
export const useLocation = RR.useLocation;
export const useNavigate = RR.useNavigate;
export const useParams = RR.useParams;
export const useSearchParams = RR.useSearchParams;
export const useMatch = RR.useMatch;
export const useRoutes = RR.useRoutes;
export const useHref = RR.useHref;
export const useResolvedPath = RR.useResolvedPath;
export const useNavigationType = RR.useNavigationType;
export const useInRouterContext = RR.useInRouterContext;
export const useOutlet = RR.useOutlet;
export const useOutletContext = RR.useOutletContext;
export const matchPath = RR.matchPath;
export const matchRoutes = RR.matchRoutes;
export const createSearchParams = RR.createSearchParams;
export const generatePath = RR.generatePath;
export const resolvePath = RR.resolvePath;
