import * as RR from "react-router-dom";
export const {
  HashRouter: BrowserRouter,
  HashRouter,
  MemoryRouter,
  Routes,
  Route,
  Link,
  NavLink,
  Navigate,
  Outlet,
  useLocation,
  useNavigate,
  useParams,
  useSearchParams,
  useMatch,
  useRoutes,
  useHref,
  useResolvedPath,
  useNavigationType,
  useInRouterContext,
  useOutlet,
  useOutletContext,
  matchPath,
  matchRoutes,
  createSearchParams,
  generatePath,
  resolvePath,
} = RR;
